package app.tasker.core.parser

import app.tasker.core.model.Bucket
import java.time.DayOfWeek

/** The ru, uk and en packs (tech plan §9.2) and the language-neutral pack used for numbers alone. */
internal object LanguagePacks {
    val Russian = LanguagePack(
        code = "ru",
        distinctiveLetters = "ыэъё",
        relativeDays = mapOf("сегодня" to 0, "завтра" to 1, "послезавтра" to 2),
        weekdays = forms(
            DayOfWeek.MONDAY to "понедельник понедельника понедельнику пн",
            DayOfWeek.TUESDAY to "вторник вторника вторнику вт",
            DayOfWeek.WEDNESDAY to "среда среду среды среде ср",
            DayOfWeek.THURSDAY to "четверг четверга четвергу чт",
            DayOfWeek.FRIDAY to "пятница пятницу пятницы пятнице пт",
            DayOfWeek.SATURDAY to "суббота субботу субботы субботе сб",
            DayOfWeek.SUNDAY to "воскресенье воскресенья воскресенью вс",
        ),
        abbreviations = "пн вт ср чт пт сб вс янв фев февр мар апр июн июл авг сен сент окт ноя нояб дек г ч след",
        nextModifiers = "следующий следующую следующее следующего следующей следующему след",
        thisModifiers = "этот эту это этого этой этому ближайший ближайшую ближайшее ближайшего ближайшей ближайшему",
        datePrepositions = mapOf("в" to false, "во" to false, "на" to true),
        months = forms(
            1 to "января янв",
            2 to "февраля фев февр",
            3 to "марта мар",
            4 to "апреля апр",
            5 to "мая",
            6 to "июня июн",
            7 to "июля июл",
            8 to "августа авг",
            9 to "сентября сен сент",
            10 to "октября окт",
            11 to "ноября ноя нояб",
            12 to "декабря дек",
        ),
        ordinalSuffixes = "го",
        yearWords = "г года году",
        offsetPrepositions = "через",
        offsetUnits = forms(
            OffsetUnit.DAYS to "день дня дней сутки суток",
            OffsetUnit.WEEKS to "неделю недели недель",
            OffsetUnit.MONTHS to "месяц месяца месяцев",
        ),
        numberWords = forms(
            1 to "один одну",
            2 to "два две пару",
            3 to "три",
            4 to "четыре",
            5 to "пять",
            6 to "шесть",
            7 to "семь",
            8 to "восемь",
            9 to "девять",
            10 to "десять",
        ),
        nextWeek = combine("следующей следующую следующая след", "неделе неделю недели неделя"),
        horizons = mapOf(
            "на неделе" to Bucket.WEEK,
            "на этой неделе" to Bucket.WEEK,
            "когда-нибудь" to Bucket.SOMEDAY,
            "когда нибудь" to Bucket.SOMEDAY,
        ),
        markers = listOf("до", "к", "ко", "не позже", "не позднее"),
        nounMarkers = listOf("дедлайн", "срок", "крайний срок"),
        bareHourMarkers = "к ко",
        timePrepositions = "в",
        dayPeriods = forms(
            DayPeriod.MORNING to "утра",
            DayPeriod.AFTERNOON to "дня",
            DayPeriod.EVENING to "вечера",
            DayPeriod.NIGHT to "ночи",
        ),
        hourWords = "час часа часов часам ч",
        countNouns = "раз раза штук штуки штука шт человек человека чел лет года рублей рубля рубль руб р тыс тысяч млн " +
            "км кг г мин минут минуты минуту сек секунд процентов процента страниц страницы стр листов этапа этапов " +
            "пунктов пункта задач задачи дней недель месяцев шагов шага вопросов вопроса глав главы мест баллов",
        alreadyDone = listOf("уже сделал", "уже сделала", "уже сделали", "уже сделано"),
        alreadyDoneWithColon = listOf("сделано"),
        rangeStarts = "с со",
        blockingWords = "каждый каждую каждое каждого каждой каждые после кроме",
        danglingWords = "в во к ко до на у о об с со",
    )

    val Ukrainian = LanguagePack(
        code = "uk",
        distinctiveLetters = "іїєґ",
        relativeDays = mapOf("сьогодні" to 0, "завтра" to 1, "післязавтра" to 2),
        weekdays = forms(
            DayOfWeek.MONDAY to "понеділок понеділка понеділку пн",
            DayOfWeek.TUESDAY to "вівторок вівторка вівторку вт",
            DayOfWeek.WEDNESDAY to "середа середу середи середі ср",
            DayOfWeek.THURSDAY to "четвер четверга четвергу чт",
            DayOfWeek.FRIDAY to "п'ятниця п'ятницю п'ятниці пт",
            DayOfWeek.SATURDAY to "субота суботу суботи суботі сб",
            DayOfWeek.SUNDAY to "неділя неділю неділі нд",
        ),
        abbreviations = "пн вт ср чт пт сб нд січ лют бер квіт трав черв лип серп вер жовт лист груд р год",
        nextModifiers = "наступний наступну наступне наступного наступної наступному наступній",
        thisModifiers = "цей цю це цього цієї цьому цій найближчий найближчу найближче найближчого найближчої найближчому",
        datePrepositions = mapOf("у" to false, "в" to false, "на" to true),
        months = forms(
            1 to "січня січ",
            2 to "лютого лют",
            3 to "березня бер",
            4 to "квітня квіт",
            5 to "травня трав",
            6 to "червня черв",
            7 to "липня лип",
            8 to "серпня серп",
            9 to "вересня вер",
            10 to "жовтня жовт",
            11 to "листопада лист",
            12 to "грудня груд",
        ),
        ordinalSuffixes = "го",
        yearWords = "р року рік",
        offsetPrepositions = "через",
        offsetUnits = forms(
            OffsetUnit.DAYS to "день дні днів дня добу",
            OffsetUnit.WEEKS to "тиждень тижні тижнів тижня",
            OffsetUnit.MONTHS to "місяць місяці місяців місяця",
        ),
        numberWords = forms(
            1 to "один одну",
            2 to "два дві пару",
            3 to "три",
            4 to "чотири",
            5 to "п'ять",
            6 to "шість",
            7 to "сім",
            8 to "вісім",
            9 to "дев'ять",
            10 to "десять",
        ),
        nextWeek = listOf("наступного тижня", "наступному тижні", "наступний тиждень"),
        horizons = mapOf(
            "цього тижня" to Bucket.WEEK,
            "на цьому тижні" to Bucket.WEEK,
            "на тижні" to Bucket.WEEK,
            "колись" to Bucket.SOMEDAY,
            "коли-небудь" to Bucket.SOMEDAY,
            "коли небудь" to Bucket.SOMEDAY,
        ),
        markers = listOf("до", "не пізніше"),
        nounMarkers = listOf("дедлайн", "термін", "крайній термін"),
        timePrepositions = "о об в",
        dayPeriods = forms(
            DayPeriod.MORNING to "ранку",
            DayPeriod.AFTERNOON to "дня",
            DayPeriod.EVENING to "вечора",
            DayPeriod.NIGHT to "ночі",
        ),
        hourWords = "година години годин годину годині год",
        countNouns = "раз рази разів штук штуки шт людей людини осіб років роки рік гривень гривні грн км кг хв хвилин " +
            "хвилини сек відсотків відсотка сторінок сторінки стор етапів етапи пунктів пункти завдань днів тижнів " +
            "місяців кроків питань",
        alreadyDone = listOf("вже зробив", "вже зробила", "вже зробили", "вже зроблено"),
        alreadyDoneWithColon = listOf("зроблено"),
        rangeStarts = "з із зі від",
        blockingWords = "кожен кожний кожну кожне кожного кожної кожні після крім",
        danglingWords = "у в до на о об з із",
    )

    val English = LanguagePack(
        code = "en",
        relativeDays = mapOf(
            "today" to 0,
            "tonight" to 0,
            "tomorrow" to 1,
            "tmrw" to 1,
            "tmr" to 1,
            "day after tomorrow" to 2,
            "the day after tomorrow" to 2,
        ),
        weekdays = forms(
            DayOfWeek.MONDAY to "monday mon",
            DayOfWeek.TUESDAY to "tuesday tue tues",
            DayOfWeek.WEDNESDAY to "wednesday wed",
            DayOfWeek.THURSDAY to "thursday thu thur thurs",
            DayOfWeek.FRIDAY to "friday fri",
            DayOfWeek.SATURDAY to "saturday sat",
            DayOfWeek.SUNDAY to "sunday sun",
        ),
        contextWeekdays = "wed sat sun",
        abbreviations = "mon tue tues wed thu thur thurs fri sat sun jan feb mar apr jun jul aug sep sept oct nov dec",
        nextModifiers = "next",
        thisModifiers = "this",
        datePrepositions = mapOf("on" to false, "for" to true),
        months = forms(
            1 to "january jan",
            2 to "february feb",
            3 to "march mar",
            4 to "april apr",
            5 to "may",
            6 to "june jun",
            7 to "july jul",
            8 to "august aug",
            9 to "september sep sept",
            10 to "october oct",
            11 to "november nov",
            12 to "december dec",
        ),
        monthBeforeDay = true,
        dayMonthJoiners = "of",
        ordinalSuffixes = "st nd rd th",
        offsetPrepositions = "in",
        offsetUnits = forms(
            OffsetUnit.DAYS to "day days",
            OffsetUnit.WEEKS to "week weeks",
            OffsetUnit.MONTHS to "month months",
        ),
        numberWords = forms(
            1 to "a an one",
            2 to "two",
            3 to "three",
            4 to "four",
            5 to "five",
            6 to "six",
            7 to "seven",
            8 to "eight",
            9 to "nine",
            10 to "ten",
        ),
        nextWeek = listOf("next week"),
        horizons = mapOf("this week" to Bucket.WEEK, "someday" to Bucket.SOMEDAY, "some day" to Bucket.SOMEDAY),
        markers = listOf("by", "no later than"),
        nounMarkers = listOf("due", "deadline"),
        timePrepositions = "at",
        hourWords = "o'clock h",
        countNouns = "times items pcs pieces people persons pages page percent km kg lbs usd eur dollars euros minutes " +
            "mins min hours hrs days weeks months years points steps tasks more less",
        alreadyDone = listOf("already did", "already done"),
        alreadyDoneWithColon = listOf("done"),
        rangeStarts = "from",
        blockingWords = "every after except",
        danglingWords = "on at by",
    )

    /** Numeric dates, times and am/pm work without any language. */
    val Neutral = LanguagePack(code = null)

    val all: List<LanguagePack> = listOf(Russian, Ukrainian, English)
}
